### ISSUE TITLE
`bug` Azure Safety Content wokshop.

### ISSUE THREAD

**Issue by nguefackuriel** [Azure/responsible-ai-hub#11]
`bug` In the Azure safety content workshop, I have the error message above when trying to open the web page:
https://playground.globalai.community/

![428C91CE-3A4C-47C1-9809-8BA3039AD58C](https://github.com/Azure/responsible-ai-hub/assets/74467653/e81b81f8-3421-4bd1-9ca3-be457da38d04)

I would appreciate to get assistance

**Comment by ruyakubu** [comment]
@nguefackuriel ...You should be able to access the Playground now. Please follow the Getting Started steps for lab# 6: https://azure.github.io/responsible-ai-hub/docs/openai-playground/

**Comment by ruyakubu** [comment]
issue closed.
