### ISSUE TITLE
[EVENT FOR CALENDAR] Zindi Community Event

### ISSUE THREAD

**Issue by rytester** [Azure/responsible-ai-hub#12]
## Event Title
Microsoft & Zindi Responsible AI day

## Event Location
Lagos, Nigeria

## Registration Page
https://aka.ms/rai-hub/website

## Workshops 
(Put an "X" inside the "[ ]" if you are running that workshop)
- [ ] Responsible AI Dashboard
- [X] Azure Content Safety
- [ ] Azure Prompt Flow

## Instructors
(You must have earned a Responsible AI Coach badge. Provide the following information for each valid instructor, and we'll add you to our Coaches page)
- Instructor Name:  Rose Ma
- Instructor Bio: facilitator of training
- Instructor Link: http://i.dont.care

**Comment by nitya** [comment]
Test entry for validation only.
