### ISSUE TITLE
[EVENT FOR CALENDAR] Zindi Community Event

### ISSUE THREAD

**Issue by nguefackuriel** [Azure/responsible-ai-hub#18]
## Event Title
Microsoft Responsible AI training workshop

## Event Location
National Higher Polytechnic School of Douala, Douala, Cameroon

## Registration Page
https://lu.ma/wugq0zrv

## Workshops 
(Put an "X" inside the "[ ]" if you are running that workshop)
- [X] Responsible AI Dashboard
- [X] Azure Content Safety
- [ ] Azure Prompt Flow

## Instructors
(You must have earned a Responsible AI Coach badge. Provide the following information for each valid instructor, and we'll add you to our Coaches page)
- Uriel Nguefack Yefou
- I am an Industrial Robotic Engineer and also a Data Scientist who graduated from the AIMS(African Institute for Mathematical Sciences) Cameroon and the National Higher Polytechnic School of Douala(NHPSD). I have a strong interest in Computer Vision, Machine Learning, Internet of Things, and Robotics. I am more focused on applying AI to the Security, Healthcare, Agriculture, Environment, and Transportation sectors
- https://www.linkedin.com/in/uriel-nguefack-yefou/

**Comment by ruyakubu** [comment]
Hi @nguefackuriel ...fantastic!  your event has been published.  For future references, the Azure subscriptions accounts are provided for participants.  Next, we need 24hrs for the event to be submitted.

Please send Zindi the **full name and emails** of the attendees to receive their badges for completing this workshop.

Cheers.

**Comment by ruyakubu** [comment]
event published.
