### ISSUE TITLE
RESPONSIBLE AI WORKSHOP

### ISSUE THREAD

**Issue by GRACENGARI** [Azure/responsible-ai-hub#21]
RESPONSIBLE AI WORKSHOP
VIRTUAL       7.30PM-9PM EAT 27/2/2024

## Registration Page
https://lu.ma/x7v7wvxh

## Workshops 
(Put an "X" inside the "[ ]" if you are running that workshop)
- [ X] Responsible AI Dashboard
- [X ] Azure Content Safety
- [ ] Azure Prompt Flow

## Instructors
(You must have earned a Responsible AI Coach badge. Provide the following information for each valid instructor, and we'll add you to our Coaches page)
GRACE NGARI
- ZINDI CAMPUS AMBASSADOR@ MERU UNIVERSITY
https://www.linkedin.com/in/grace-ngari-2b8a01245/

**Comment by ruyakubu** [comment]
Hi @GRACENGARI ...thanks for submitting your event.

Please add the workshop details to the registration page and badge awards:

**Workshop Overview**

Responsible AI is a critical part of machine learning. With the recent breakthroughs in AI, there is increasing societal scrutiny for AI to be regulated. However, data scientists and AI developers need practical tools to enable them to safe-guide, debug, mitigate and deliver AI solutions that are less harmful and more trustworthy. Participants will learn best practices using vectors, prompt engineering and detecting harmful AI issues such as biases, jailbreaks, hallucination and offensive content.

**Awards**
Upon completion of the workshop, participants will be awarded an Azure Responsible AI badges.

Once, you've updated the changes, let us know to post your event.

**Comment by ruyakubu** [comment]
Event added.  Thanks
