### ISSUE TITLE
Microsoft Responsible AI Workshop

### ISSUE THREAD

**Issue by Dorothy2020** [Azure/responsible-ai-hub#22]
RESPONSIBLE AI WORKSHOP
Location : Zoom
Time: 7.30PM-9:30PM EAT
Date: 27/2/2024

Registration Page
https://lu.ma/x7v7wvxh

Workshops
(Put an "X" inside the "[ ]" if you are running that workshop)

[ X] Responsible AI Dashboard
[X ] Azure Content Safety
 Azure Prompt Flow
Instructors
(You must have earned a Responsible AI Coach badge. Provide the following information for each valid instructor, and we'll add you to our Coaches page)
Dorothy Akoth

Zindi Community Ambassador
linkedIn:https://www.linkedin.com/in/dorothy-akoth/

**Comment by ruyakubu** [comment]
@Dorothy2020....What's the location of the workshop?  

Next, you'll need to add the workshop details to the registration page and badge awards:

**Workshop Overview** 

Responsible AI is a critical part of machine learning.  With the recent breakthroughs in AI, there is increasing societal scrutiny for AI to be regulated.  However, data scientists and AI developers need practical tools to enable them to safe-guide, debug, mitigate and deliver AI solutions that are less harmful and more trustworthy.   Participants will learn best practices using vectors, prompt engineering and detecting harmful AI issues such as biases, jailbreaks, hallucination and offensive content. 

**Awards** 
Upon completion of the workshop, participants will be awarded an **Azure Responsible AI badges**. 

Once, you've updated the changes, let us know to post your event.

**Comment by Dorothy2020** [comment]
> @Dorothy2020....What's the location of the workshop?
> 
> Next, you'll need to add the workshop details to the registration page and badge awards:
> 
> **Workshop Overview**
> 
> Responsible AI is a critical part of machine learning. With the recent breakthroughs in AI, there is increasing societal scrutiny for AI to be regulated. However, data scientists and AI developers need practical tools to enable them to safe-guide, debug, mitigate and deliver AI solutions that are less harmful and more trustworthy. Participants will learn best practices using vectors, prompt engineering and detecting harmful AI issues such as biases, jailbreaks, hallucination and offensive content.
> 
> **Awards** Upon completion of the workshop, participants will be awarded an **Azure Responsible AI badges**.
> 
> Once, you've updated the changes, let us know to post your event.



> RESPONSIBLE AI WORKSHOP Location : Zoom Time: 7.30PM-9PM EAT Date: 27/2/2024
> 
> Registration Page https://lu.ma/x7v7wvxh
> 
> Workshops (Put an "X" inside the "[ ]" if you are running that workshop)
> 
> [ X] Responsible AI Dashboard [X ] Azure Content Safety Azure Prompt Flow Instructors (You must have earned a Responsible AI Coach badge. Provide the following information for each valid instructor, and we'll add you to our Coaches page) Dorothy Akoth
> 
> Zindi Community Ambassador linkedIn:https://www.linkedin.com/in/dorothy-akoth/

**Comment by Dorothy2020** [comment]
@ruyakubu I have updated the location ,you can check on my updated open issue

**Comment by ruyakubu** [comment]
Got it.   Event Closed

**Comment by Dorothy2020** [comment]
> Got it. Event Added.

Thank you @ruyakubu we are using this link for registration https://lu.ma/w71bjcop, it entails the event details and description
