### ISSUE TITLE
Responsible AI Workshop

### ISSUE THREAD

**Issue by grctutu** [Azure/responsible-ai-hub#23]
## Event Title
Responsible AI Workshop.

## Event Location
Kenyatta University, Nairobi, Kenya

## Registration Page
https://lu.ma/o9fklaxp

## Workshops 
(Put an "X" inside the "[ ]" if you are running that workshop)
- [X ] Responsible AI Dashboard
- [ ] Azure Content Safety
- [ ] Azure Prompt Flow

## Instructors
(You must have earned a Responsible AI Coach badge. Provide the following information for each valid instructor, and we'll add you to our Coaches page)
- Instructor Name
Grace Mutinda 
- Instructor Bio
Grace Mutinda is a stem Educator in the field of Robotics and AI. She collaborates with international schools in Kenya to leverage coding skills to young minds. Grace is also a Zindi ambassador and a community manager with DSEAfrica.

- Instructor Link (to website or social)
Twitter: https://x.com/grctutu?t=CVOSjN1_ztc9QATY81I2Og&s=09

LinkedIn: https://www.linkedin.com/in/grace-mutinda-a35816216?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app

**Comment by ruyakubu** [comment]
event added.

**Comment by ruyakubu** [comment]
closing this item
