### ISSUE TITLE
Zindi Community Event

### ISSUE THREAD

**Issue by isaacnewt** [Azure/responsible-ai-hub#24]
## Event Title
Implementing Responsible AI using Microsoft Azure 

## Event Location
Alet-Eleme, Rivers State, Nigeria

## Registration Page
https://lu.ma/oqwoa774

## Workshops 

- [x ] Responsible AI Dashboard
- [x ] Azure Content Safety
- [x ] Azure Prompt Flow

## Instructors
(You must have earned a Responsible AI Coach badge. Provide the following information for each valid instructor, and we'll add you to our Coaches page)
- Isaac Ikwuegbu 
- An astute ambassador of Zindi, Isaac has been responsible for fostering the new generation of AI army in his country home of Nigeria. During his spare time, Isaac enjoys solving mathematical riddles.
- https://www.linkedin.com/in/isaacikwegbu

**Comment by ruyakubu** [comment]
Thanks for your event submission @isaacnewt.  Your event is now added to the website Calendar.
