### ISSUE TITLE
[EVENT FOR CALENDAR] Zindi Community Event

### ISSUE THREAD

**Issue by Atwiine75** [Azure/responsible-ai-hub#26]
## Event Title
(AI in it's simplest form)

## Event Location
(Kampala uganda)

## Registration Page
(https://lu.ma/fn0z4cku)

## Workshops 
(Put an "X" inside the "[ ]" if you are running that workshop)
- [x ] Responsible AI Dashboard
- [ x] Azure Content Safety
- [ x] Azure Prompt Flow

## Instructors
(You must have earned a Responsible AI Coach badge. Provide the following information for each valid instructor, and we'll add you to our Coaches page)
- Instructor Name Atwiine Innocent
- Instructor Bio 3 years experience in AI
- Instructor Link (to website or social) https://www.linkedin.com/in/atwiine-innocent-bb8851255?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app

**Comment by ruyakubu** [comment]
Thanks for submitting your event.  It's now added to the calendar.
