### ISSUE TITLE
[EVENT FOR CALENDAR] Zindi Community Event

### ISSUE THREAD

**Issue by nguefackuriel** [Azure/responsible-ai-hub#28]
## Event Title
Microsoft Responsible AI training workshop

## Event Location
IUT Douala, Cameroon

## Registration Page
https://lu.ma/kuv9rts6

## Workshops 
(Put an "X" inside the "[ ]" if you are running that workshop)
- [X] Responsible AI Dashboard
- [X] Azure Content Safety
- [X] Azure Prompt Flow

## Instructors
(You must have earned a Responsible AI Coach badge. Provide the following information for each valid instructor, and we'll add you to our Coaches page)
- Uriel Nguefack Yefou
- I am an Industrial Robotic Engineer and also a Data Scientist who graduated from the AIMS(African Institute for Mathematical Sciences) Cameroon and the National Higher Polytechnic School of Douala(NHPSD). I have a strong interest in Computer Vision, Machine Learning, Internet of Things, and Robotics. I am more focused on applying AI to the Security, Healthcare, Agriculture, Environment, and Transportation sectors
- https://www.linkedin.com/in/uriel-nguefack-yefou/

**Comment by ruyakubu** [comment]
Thanks for submitting an event @nguefackuriel.   The event has been added to the calendar.

**Comment by ruyakubu** [comment]
closing request.
