### ISSUE TITLE
Code Space Recovery Mode Error

### ISSUE THREAD

**Issue by Robert-Selemani** [Azure/responsible-ai-hub#37]
### Discussed in https://github.com/Azure/responsible-ai-hub/discussions/36

<div type='discussions-op-text'>

<sup>Originally posted by **Robert-Selemani** March  9, 2024</sup>
![Error 1](https://github.com/Azure/responsible-ai-hub/assets/61738125/0fa7396a-7a5c-4c25-bda0-ffe91716bbc0)

Good morning. I am facilitating a training in 3 hours, and I am getting this error. How can I resolve it? Anyone to assist step by step? I can't happen to succeed in helping myself just from the error message. Thanks.</div>

**Comment by ruyakubu** [comment]
issue resolved.
